student_management_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from student_management_app import api_views, api_HodViews, api_StaffViews, api_StudentViews
from student_management_system import settings

urlpatterns = [
path('api-auth/', include('rest_framework.urls')),
    path('api/signup_student/',api_views.do_signup_student,name="signup_student"),
    path('api/do_admin_signup',api_views.do_admin_signup,name="do_admin_signup"),
    path('api/do_staff_signup',api_views.do_staff_signup,name="do_staff_signup"),
    path('api/do_signup_student',api_views.do_signup_student,name="do_signup_student"),
    path('api/get_batches/', api_views.get_batches, name='get_batches_signup'),
    path('api/social-auth/', include('social_django.urls', namespace='social')),
    #/SignUpPart
    path('api/admin/', admin.site.urls),
    path('api/accounts/',include('django.contrib.auth.urls')),
    path('api/get_user_details', api_views.get_user_details),
    path('api/logout_user', api_views.logout_user,name="logout"),
    path('api/Login',api_views.dologin,name="do_login"),
    #hod_urls
    path('api/admin_home',api_HodViews.admin_home,name="admin_home"),
    path('api/add_staff_save',api_HodViews.add_staff_save,name="add_staff_save"),
    path('api/add_branch_save', api_HodViews.add_branch_save,name="add_branch_save"),
    path('api/delete_branch/<int:branch_id>/', api_HodViews.delete_branch, name='delete_branch'),
    #studentflow
    path('api/branches/', api_HodViews.branch_list, name='branch_list'),
    path('api/branches/<int:branch_id>/batches/', api_HodViews.batch_list, name='batch_list'),
    path('api/branch/<int:branch_id>/batch/<int:batch_id>/student-details/', api_HodViews.student_details,name='student_details'),
    path('api/branch/<int:branch_id>/batch/<int:batch_id>/add_student_save/', api_HodViews.add_student_save,name='add_student_save'),
    path('api/branch/<int:branch_id>/batch/<int:batch_id>/manage/', api_HodViews.manage_students,name='manage_students'),
    #studentflow
    path('api/assign_staff/', api_HodViews.assign_staff, name="assign_staff"),
    #DietPlan
    path('api/upload_diet_plan/', api_HodViews.upload_diet_plan, name='upload_diet_plan'),
    path('api/get_batches/', api_HodViews.get_batch, name='get_batch'),
    path('api/get_students/', api_HodViews.get_student, name='get_student'),
    path('api/diet_plan_list/', api_HodViews.diet_plan_list, name='diet_plan_list'),
    #/DietPlan
    path('api/delete_staff/<int:id>', api_HodViews.delete_staff, name='delete_staff'),
    path('api/delete_student/<int:id>/', api_HodViews.delete_student, name='delete_student'),
    path('api/delete_diet/<int:id>/', api_HodViews.delete_diet, name='delete_diet'),
    path('api/manage_staff', api_HodViews.manage_staff,name="manage_staff"),
    path('api/manage_students/<int:branch_id>/<int:batch_id>/', api_HodViews.manage_students, name='manage_students'),
    path('api/manage_branch', api_HodViews.manage_branch, name="manage_branch"),
    path('api/manage_assign', api_HodViews.manage_assign, name="manage_assign"),
    path('api/edit_staff_save', api_HodViews.edit_staff_save,name="edit_staff_save"),
    path('api/edit_student_save', api_HodViews.edit_student_save,name="edit_student_save"),
    path('api/delete-assign/<int:assignment_id>/', api_HodViews.delete_assign, name='delete_assign'),
    path('api/edit_assign_save/', api_HodViews.edit_assign_save, name='edit_assign_save'),
    # URLs for Editing Branches
    path('api/edit_branch_save', api_HodViews.edit_branch_save, name="edit_branch_save"),
    path('api/check_email_exist', api_HodViews.check_email_exist,name="check_email_exist"),
    path('api/check_username_exist', api_HodViews.check_username_exist,name="check_username_exist"),
    path('api/student_feedback_message', api_HodViews.student_feedback_message,name="student_feedback_message"),
    path('api/student_feedback_message_replied', api_HodViews.student_feedback_message_replied,name="student_feedback_message_replied"),
    path('api/staff_leave_view', api_HodViews.staff_leave_view,name="staff_leave_view"),
    path('api/staff_disapprove_leave/<str:leave_id>', api_HodViews.staff_disapprove_leave,name="staff_disapprove_leave"),
    path('api/staff_approve_leave/<str:leave_id>', api_HodViews.staff_approve_leave,name="staff_approve_leave"),
    #Admin_ViewAttendance
    path('api/admin_view_attendance', api_HodViews.admin_view_attendance,name="admin_view_attendance"),
    path('api/admin_get_batches', api_HodViews.admin_get_batches, name="admin_get_batches"),
    path('api/admin_get_attendance_dates', api_HodViews.admin_get_attendance_dates,name="admin_get_attendance_dates"),
    path('api/admin_get_attendance_student', api_HodViews.admin_get_attendance_students,name="admin_get_attendance_student"),
    #Admin_ViewAttendance
    path('api/admin_profile', api_HodViews.admin_profile,name="admin_profile"),
    path('api/admin_profile_save', api_HodViews.admin_profile_save,name="admin_profile_save"),
    path('api/admin_send_notification_staff', api_HodViews.admin_send_notification_staff,name="admin_send_notification_staff"),
    path('api/admin_send_notification_student', api_HodViews.admin_send_notification_student,name="admin_send_notification_student"),
    path('api/send_student_notification', api_HodViews.send_student_notification,name="send_student_notification"),
    path('api/send_staff_notification', api_HodViews.send_staff_notification,name="send_staff_notification"),




  #     Staff URL Path
    path('api/staff_home', api_StaffViews.staff_home, name="staff_home"),
    # path('api/get_batches_by_branch/', api_StaffViews.get_batches_by_branch, name='get_batches_by_branch'),
    # path('api/get_students_by_batch/', api_StaffViews.get_students_by_batch, name='get_students_by_batch'),
    #StudentUnderMe
    path('api/view-students', api_StaffViews.staff_view_students, name='staff_view_students'),
    path('api/get_batches_by_branch/', api_StaffViews.get_batches_by_branch, name='get_batches_by_branch'),
    path('api/get_students_by_branch_and_batch/', api_StaffViews.get_students_by_branch_and_batch,name='get_students_by_branch_and_batch'),
    #/StudentUnderMe
    path('api/staff_take_attendance', api_StaffViews.staff_take_attendance, name="staff_take_attendance"),
    path('api/staff_update_attendance', api_StaffViews.staff_update_attendance, name="staff_update_attendance"),
    path('api/get-batches/', api_StaffViews.get_batches, name='get_batches'),
    path('api/get_students', api_StaffViews.get_students, name="get_students"),
    path('api/get_attendance_dates', api_StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('api/get_attendance_student', api_StaffViews.get_attendance_student, name="get_attendance_student"),
    path('api/save_attendance_data', api_StaffViews.save_attendance_data, name="save_attendance_data"),
    path('api/save_updateattendance_data', api_StaffViews.save_updateattendance_data, name="save_updateattendance_data"),
    path('api/staff_apply_leave', api_StaffViews.staff_apply_leave, name="staff_apply_leave"),
    path('api/staff_apply_leave_save', api_StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('api/staff_profile', api_StaffViews.staff_profile, name="staff_profile"),
    path('api/staff_profile_save', api_StaffViews.staff_profile_save, name="staff_profile_save"),
    path('api/staff_fcmtoken_save', api_StaffViews.staff_fcmtoken_save, name="staff_fcmtoken_save"),
    path('api/staff_all_notification', api_StaffViews.staff_all_notification, name="staff_all_notification"),



    #Student
    path('api/student_home', api_StudentViews.student_home, name="student_home"),
    path('api/student_view_attendance', api_StudentViews.student_view_attendance, name="student_view_attendance"),
    path('api/student_view_attendance_post', api_StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    #ViewDiet
    path('api/my_diet_plans/', api_StudentViews.student_diet_plans, name='student_diet_plans'),
    #/ViewDiet
    path('api/student_feedback', api_StudentViews.student_feedback, name="student_feedback"),
    path('api/student_feedback_save', api_StudentViews.student_feedback_save, name="student_feedback_save"),
    path('api/student_profile', api_StudentViews.student_profile, name="student_profile"),
    path('api/student_profile_save', api_StudentViews.student_profile_save, name="student_profile_save"),
    path('api/student_fcmtoken_save', api_StudentViews.student_fcmtoken_save, name="student_fcmtoken_save"),
    path('api/firebase-messaging-sw.js',api_views.get_firebase_config,name="show_firebase_js"),
    path('api/student_all_notification',api_StudentViews.student_all_notification,name="student_all_notification")
#/Student
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

student_management_app/forms.py
from django import forms
from student_management_app.models import Batch, Branches, Student

class DateInput(forms.DateInput):
    input_type = "date"


class AddStudentForm(forms.Form):
    email = forms.EmailField(
        label="Email", max_length=50,
        widget=forms.EmailInput(attrs={"class": "form-control", "autocomplete": "off"})
    )
    password = forms.CharField(
        label="Password", max_length=50,
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    first_name = forms.CharField(
        label="First Name", max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        label="Last Name", max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    username = forms.CharField(
        label="Username", max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control", "autocomplete": "off"})
    )
    dob = forms.DateField(
        label="Date of Birth",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"})
    )
    contact = forms.CharField(
        label="Contact", max_length=15,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    gender_choice = [
        ("Male", "Male"),
        ("Female", "Female")
    ]
    gender = forms.ChoiceField(
        label="Gender", choices=gender_choice,
        widget=forms.Select(attrs={"class": "form-control"})
    )
    profile_pic = forms.FileField(
        label="Profile Pic", max_length=50,
        widget=forms.FileInput(attrs={"class": "form-control"}),
        required=False
    )



class EditStudentForm(forms.Form):
    email = forms.EmailField(
        label="Email", max_length=50,
        widget=forms.EmailInput(attrs={"class": "form-control"})
    )
    first_name = forms.CharField(
        label="First Name", max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        label="Last Name", max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    username = forms.CharField(
        label="Username", max_length=50,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    gender_choice = [
        ("Male", "Male"),
        ("Female", "Female")
    ]
    gender = forms.ChoiceField(
        label="Gender", choices=gender_choice,
        widget=forms.Select(attrs={"class": "form-control"})
    )
    contact = forms.CharField(
        label="Contact", max_length=15,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    dob = forms.DateField(
        label="Date of Birth",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"})
    )
    branch = forms.ModelChoiceField(
        queryset=Branches.objects.all(),
        label="Branch", widget=forms.Select(attrs={"class": "form-control"})
    )
    batch = forms.ModelChoiceField(
        queryset=Batch.objects.all(),
        label="Batch", widget=forms.Select(attrs={"class": "form-control"})
    )
    profile_pic = forms.FileField(
        label="Profile Pic", max_length=50,
        widget=forms.FileInput(attrs={"class": "form-control"}),
        required=False
    )

from django import forms
from .models import StaffBranchAssignment, Branches, CustomUser

# forms.py

from django import forms
from .models import StaffBranchAssignment, Branches, CustomUser

class AssignStaffForm(forms.ModelForm):
    class Meta:
        model = StaffBranchAssignment
        fields = ['staff', 'branch']
        widgets = {
            'staff': forms.Select(attrs={'class': 'form-control'}),
            'branch': forms.Select(attrs={'class': 'form-control'}),
        }

#DietPlan

from django import forms
from .models import DietPlans, Branches, Batch, Student

class DietPlanForm(forms.ModelForm):
    branch = forms.ModelChoiceField(queryset=Branches.objects.all(), label="Branch")
    batch = forms.ModelChoiceField(queryset=Batch.objects.all(), label="Batch", required=False)
    students = forms.ModelMultipleChoiceField(queryset=Student.objects.all(), widget=forms.CheckboxSelectMultiple, label="Students", required=False)

    class Meta:
        model = DietPlans
        fields = ['title', 'pdf', 'branch', 'batch', 'students']

#/DietPLan

student_management_app/templates/hod_template/add_staff_template.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Add Staff
{% endblock page_title %}
{% block main_content %}
<!-- Main content -->
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
               <div class="card-header">
                  <h3 class="card-title">Add Staff</h3>
               </div>
               <!-- /.card-header -->
               <!-- form start -->
               <form role="form" action="/add_staff_save" method="post">
                  {% csrf_token %}
                  <div class="card-body">
                     <div class="form-group">
                        <label>Email address</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                     </div>
                     <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Password" name="password">
                     </div>
                     <div class="form-group">
                        <label>First Name</label>
                        <input type="text" class="form-control" placeholder="First Name" name="first_name" autocomplete="off">
                     </div>
                     <div class="form-group">
                        <label>Last Name</label>
                        <input type="text" class="form-control" placeholder="Last Name" name="last_name" autocomplete="off">
                     </div>
                     <div class="form-group">
                        <label>Username</label>
                        <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="on">
                     </div>
                     <div class="form-group">
                        <label>Address</label>
                        <input type="text" class="form-control" placeholder="Address" name="address" autocomplete="off">
                     </div>
                     <div class="form-group">
                        {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                     </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                     <button type="submit" class="btn btn-primary btn-block">Add Staff</button>
                  </div>
               </form>
            </div>
            <!-- /.card -->
         </div>
      </div>
   </div>
</section>
<!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
   $(document).ready(function(){
       $("#id_email").keyup(function(){
           var email=$(this).val();

          if(email!=""){
               $.ajax({
                   url:'{% url 'check_email_exist' %}',
                   type:'POST',
                   data:{email:email}
               })
               .done(function(response){
                   console.log(response);
                   if(response=="True"){
                       $(".email_error").remove();
                       $("<span class='email_error' style='padding: 5px;color: red;font-weight: bold;'>Email Not Available</span>").insertAfter("#id_email");
                   }
                   else{
                       $(".email_error").remove();
                       $("<span class='email_error' style='padding: 5px;color: green;font-weight: bold;'>Email Available</span>").insertAfter("#id_email");
                   }
               })
               .fail(function(){
                   console.log("failed");
               })
           }
           else{
             $(".email_error").remove();
           }

       });

       $("#id_username").keyup(function(){
           var username=$(this).val();

           if(username!=""){
               $.ajax({
                   url:'{% url 'check_username_exist' %}',
                   type:'POST',
                   data:{username:username}
               })
               .done(function(response){
                   console.log(response);
                   if(response=="True"){
                       $(".username_error").remove();
                       $("<span class='username_error' style='padding: 5px;color: red;font-weight: bold;'>Username Not Available</span>").insertAfter("#id_username");
                   }
                   else{
                       $(".username_error").remove();
                       $("<span class='username_error' style='padding: 5px;color: green;font-weight: bold;'>Username Available</span>").insertAfter("#id_username");
                   }
               })
               .fail(function(){
                   console.log("failed");
               })
           }
           else{
               $(".username_error").remove();
           }

       });

   });
</script>
{% endblock custom_js %}

student_management_app/templates/hod_template/admin_profile.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Edit Profile
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Profile</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'admin_profile_save' %}" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.username }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.email }}" disabled="disabled">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}">
                  </div>
                  <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}">
                  </div>
                   <div class="form-group">
                    <label>Change Password?</label>
                    <input type="text" class="form-control" name="password" placeholder="Fill Only If You want to Change Password">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Save Profile</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/hod_template/batch_list.html
{% extends 'hod_template/base_template.html' %}

{% block page_title %}
Batch List
{% endblock page_title %}

{% block main_content %}
<!-- Main content -->
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12">
            <!-- Batch List -->
            <div class="card">
               <div class="card-header">
                  <h3 class="card-title">Batches for {{ branch.branch_name }}</h3>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <ul>
                     {% for batch in batches %}
                     <li>
                            <a href="{% url 'student_details' branch.id batch.id %}" class="btn btn-info">{{ batch.template.name }}</a>
                     </li>
                     {% empty %}
                     <li>No batches available.</li>
                     {% endfor %}
                  </ul>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
      </div>
   </div>
</section>
<!-- /.content -->
{% endblock main_content %}

{% block custom_js %}
<!-- Custom JS for this page -->
{% endblock custom_js %}

student_management_app/templates/hod_template/edit_assign_template.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Edit Assignment | Assignment ID: {{ assignment.id }}
{% endblock page_title %}
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Edit Assignment</h3>
          </div>
          <form action="{% url 'edit_assign_save' %}" method="post">
            {% csrf_token %}
            <div class="card-body">
              <div class="form-group">
                <label>Staff</label>
                <select class="form-control" name="staff">
                    {% for staff in staffs %}
                      <option value="{{ staff.id }}" {% if staff.id == assignment.staff.id %} selected {% endif %}>
                        {{ staff.first_name }} {{ staff.last_name }}
                      </option>
                    {% endfor %}
                </select>
              </div>
              <div class="form-group">
                <label>Branch</label>
                <select class="form-control" name="branch">
                    {% for branch in branches %}
                      <option value="{{ branch.id }}" {% if branch.id == assignment.branch.id %} selected {% endif %}>
                        {{ branch.branch_name }}
                      </option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <div class="card-footer">
              <input type="hidden" name="assign_id" value="{{ assignment.id }}">
              <button type="submit" class="btn btn-primary btn-block">Save Assignment</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock main_content %}

student_management_app/templates/hod_template/edit_branch_template.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Edit Branch | Branch ID: {{ branch.id }}
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Branch</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/edit_branch_save" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Branch Name</label>
                    <input type="text" class="form-control" name="branch" placeholder="Enter Branch" value="{{ branch.name }}">
                    <input type="hidden" name="branch_id" value="{{ branch.id }}">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Save Branch</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/hod_template/upload_diet_plan.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Upload Diet Plan
{% endblock page_title %}
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Upload Diet Plan</h3>
          </div>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-body">
              <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
              </div>
              <div class="form-group">
                {{ form.pdf.label_tag }}
                {{ form.pdf }}
              </div>
              <div class="form-group">
                {{ form.branch.label_tag }}
                {{ form.branch }}
              </div>
              <div class="form-group">
                <label for="batch">Select Batch</label>
                <select id="batch-select" class="form-control" name="batch">
                  <option value="">Select Batch</option>
                </select>
              </div>
              <div class="form-group">
                <label for="students">Select Students</label>
                <div id="students-list">
                  <p>No students available</p>
                </div>
              </div>
            </div>
              {% if messages %}
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                {% endif %}
                {% if message.tags == 'success' %}
                <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                {% endif %}
                {% endfor %}
              {% endif %}
            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Upload and Assign</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        // Fetch batches when a branch is selected
        $('#id_branch').change(function(){
            var branchId = $(this).val();
            if(branchId){
                $.ajax({
                    url: "{% url 'get_batch' %}",
                    type: "POST",
                    data: {
                        'branch_id': branchId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(data){
                        $('#batch-select').empty().append('<option value="">Select Batch</option>');
                        $.each(data, function(index, batch){
                            $('#batch-select').append('<option value="'+batch.id+'">'+batch.name+'</option>');
                        });
                    }
                });
            }
        });

        // Fetch students when a batch is selected
        $('#batch-select').change(function(){
            var branchId = $('#id_branch').val();
            var batchId = $(this).val();
            if(branchId && batchId){
                $.ajax({
                    url: "{% url 'get_student' %}",
                    type: "POST",
                    data: {
                        'branch_id': branchId,
                        'batch_id': batchId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(data){
                        $('#students-list').empty();
                        $.each(data, function(index, student){
                            $('#students-list').append('<input type="checkbox" name="students" value="'+student.id+'"> '+student.name+'<br>');
                        });
                    }
                });
            }
        });
    });
</script>
{% endblock main_content %}